### ISSUE TITLE
Perform version check for Treelite 3.0+

### ISSUE THREAD

**Issue by hcho3** [triton-inference-server/fil_backend#288]
Perform version check for Treelite 3.0+. When a newer versioned model is given, Triton-FIL should throw a warning about a possible incompatibility (e.g. a new feature may not be supported).

I will come back to this issue once Triton-FIL updates to cuML 22.10.

**Comment by wphicks** [comment]
After #307, we're on cuML 22.10. Do you think it likely we could get this into 23.01?

**Comment by hcho3** [comment]
@wphicks Yes, it should be straightforward to implement the version check.
