### ISSUE TITLE
Add support for CPU-only inference

### ISSUE THREAD

**Issue by wphicks** [triton-inference-server/fil_backend#41]
- [x] Merge https://github.com/dmlc/treelite/pull/274
- [x] Merge https://github.com/rapidsai/cuml/pull/3855
- [x] Merge #23
- [x] Update configuration to allow selection of CPU-only mode
- [x] Update batching to optionally prefer host arrays
- [x] Use GTIL prediction call when in CPU-only mode

**Comment by hcho3** [comment]
I've just tested cuML with the latest `mainline` branch of Treelite. I am now preparing a new release of Treelite.

**Comment by hcho3** [comment]
Reminder: Add tests on the cuML side that exports cuML RFs as Treelite checkpoints and run inference with GTIL. I actually have written the tests already.

**Comment by hcho3** [comment]
I added integration tests in #3855 that runs cuML RFs with GTIL.
