### ISSUE TITLE
Tests failing on NVIDIA Tesla T4, AWS G4 instance

### ISSUE THREAD

**Issue by hcho3** [triton-inference-server/fil_backend#80]
Tests fail when using AWS G4 instance.

Steps to reproduce:
1. Set up CUDA 11.3 (latest) and NVIDIA Docker on a fresh EC2 instance of type g4dn.8xlarge.
2. Build the trition_fil Docker image: `docker build -t triton_fil -f ops/Dockerfile .`
3. Run the CI script: `LOCAL=1 ./qa/run_tests.sh`

When I switched the instance to p3.2xlarge type (V100 GPU), the tests run successfully. 

Error messages:
* `lightgbm` model
```
AssertionError: 
Arrays are not almost equal to 7 decimals
Mismatched elements: 1 / 1 (100%)
Max absolute difference: 0.36781818
Max relative difference: 0.36781818
 x: array([0.6321818], dtype=float32)
 y: array([1.], dtype=float32)
```
* `xgboost` model
```
AssertionError:                                                                                                                                                           
Arrays are not almost equal to 7 decimals                                                                                                                                 
Mismatched elements: 1 / 1 (100%)         
Max absolute difference: 2.                                                          
Max relative difference: 1.               
 x: array([0.], dtype=float32)                                                                                                                                            
 y: array([2.], dtype=float32)
```

**Comment by wphicks** [comment]
Triage data thus far:

- Occurs consistently on T4s, including those not on AWS
- Mismatch occurs on a small number of samples in each test but is highly consistent
- Breaking in on failure and re-running the failing sample results in success
- Occurs for models with only 8 features (suggests this may be something other than a memory issue)

**Comment by wphicks** [comment]
Another note for triaging: Throughput on tests is quite high relative to V100 and RTX8000 (roughly 3 times). This may be revealing a race condition, and if so #77 may be related.
